version: "3.4"

services:
  backend:
    build:
      context: ./packages/backend
      target: backend
    image: "${PROJECT_NAME}/backend"
    command: ["./scripts/runtime/run_local.sh"]
    ports:
      - "5001:5001"
    depends_on:
      stripemock:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped
    links:
      - redis
    environment:
      - DATABASE_HOST=10.0.1.3
      - DATABASE_PORT=5432
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=z6].atnXN"l6"zq[x&^R
      - DATABASE_NAME=rdb
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-west-1
      - EMAIL_USE_TLS=True
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=noreply@cybiagence.com
      - EMAIL_HOST_PASSWORD=hzsxqwilzwvbtqbh
    stdin_open: true
    tty: true

  celery_beat:
    image: "${PROJECT_NAME}/backend"
    command: ["./scripts/runtime/run_celery_beat.sh"]
    restart: always
    depends_on:
      backend:
        condition: service_started

  celery_default:
    image: "${PROJECT_NAME}/backend"
    command: ["./scripts/runtime/run_celery_worker_default.sh"]
    restart: always
    depends_on:
      backend:
        condition: service_started

  workers:
    build:
      context: .
      dockerfile: ./packages/workers/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
    environment:
      - DATABASE_HOST=10.0.1.3
      - DATABASE_PORT=5432
      - DATABASE_USER=backend
      - DATABASE_PASSWORD=backend
      - DATABASE_NAME=backend

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  stripemock:
    image: stripe/stripe-mock:v0.170.0
    ports:
      - "12111:12111"
      - "12112:12112"

  ssm-editor:
    stdin_open: true
    tty: true
    build:
      context: ./packages/internal/ssm-editor
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-}
      - ENV_STAGE=${ENV_STAGE:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN:-}
      - AWS_SESSION_EXPIRATION=${AWS_SESSION_EXPIRATION:-}
